

 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (1, 'app_1', null, null, 0, null, '', null, null, null, '', 0, null, 0, '系统扩展表', 9, 1, null, 1, '3|8|9|1|', 'admin', '2017-01-17 12:48:11', '/sys/tableMgr/tables?type=useradd');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (3, 'app_3', null, null, 0, null, '应用模块', null, null, null, null, 1, null, 0, '应用模块', -1, 1, null, 1, '3|', null, null, null);
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (8, 'app_8', null, null, 0, null, '系统管理', null, null, null, null, 2, null, 0, '系统管理', 3, 1, null, 12, '3|8|', null, null, null);
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (9, 'app_9', null, null, 0, null, '系统设置', null, null, null, null, 3, null, 0, '系统设置', 8, 1, null, 2, '3|8|9|', null, null, null);
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (100, 'app_100', null, null, 0, null, '安全设置', null, null, null, null, 3, null, 0, '安全设置', 8, 1, null, 1, '3|8|100|', null, null, null);
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (101, 'app_101', null, null, 0, null, '模块管理', null, null, null, null, 4, null, 0, '模块管理', 100, 1, null, 6, '3|8|100|101|', null, null, '/sys/application');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (102, 'app_102', null, null, 0, null, '机构管理', null, null, null, null, 4, null, 0, '机构管理', 100, 1, null, 7, '3|8|100|102|', null, null, '/sys/organization');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (103, 'app_103', null, null, 0, null, '用户管理', null, null, null, null, 4, null, 0, '用户管理', 100, 1, null, 8, '3|8|100|103|', null, null, '/sys/user');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (104, 'app_104', null, null, 0, null, '角色管理', null, null, null, null, 4, null, 0, '角色管理', 100, 1, null, 9, '3|8|100|104|', null, null, '/sys/role');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (105, 'app_105', null, null, 0, null, '在线用户', null, null, null, null, 4, null, 0, '在线用户', 100, 1, null, 10, '3|8|100|105|', null, null, '/user/online');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (106, 'app_106', null, null, 0, null, '在线日志', null, null, null, null, 4, null, 0, '在线日志', 100, 1, null, 11, '3|8|100|106|', null, null, '/user/onlinelog');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (107, 'app_107', null, null, 0, null, '', null, null, null, '', 4, null, 1, '食品登记表', 700, 1, null, 0, '3|8|700|107|', 'admin', '2017-04-13 09:35:25', '/tableData/datalist?tableId=23714a7509504c24a7e77e3375c86d66');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (201, 'app_201', null, null, 0, null, '字典管理', null, null, null, null, 4, null, 0, '字典管理', 9, 1, null, 3, '3|8|9|201|', null, null, '/sys/dictory');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (202, 'app_202', null, null, 0, null, '缓存管理', null, null, null, null, 4, null, 0, '缓存管理', 9, 1, null, 4, '3|8|9|202|', null, null, '/sys/cacheMgr');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (203, 'app_203', null, null, 0, null, '模板管理', null, null, null, null, 4, null, 1, '模板管理', 9, 1, null, 14, '3|8|9|203|', null, null, '/sys/template/showFrame?parentId=19');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (204, 'app_204', null, null, 0, null, '系统表管理', null, null, null, null, 4, null, 0, '系统表管理', 9, 1, null, 5, '3|8|9|204|', null, null, '/sys/table');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (205, 'app_205', null, null, 0, null, '重新加载数据', null, null, null, null, 4, null, 0, '数据重载', 9, 1, null, 6, '3|8|9|205|', null, null, '/sys/dictory/loadDictory');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (206, 'app_206', null, null, 0, null, '服务器管理', null, null, null, null, 4, null, 0, '服务器管理', 9, 1, null, 7, '3|8|9|206|', null, null, '/sys/server');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (207, 'app_207', null, null, 0, null, '数据库设置', null, null, null, null, 4, null, 0, '数据库设置', 9, 1, null, 8, '3|8|9|207|', null, null, '/sys/database');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (208, 'app_208', null, null, 0, null, '实时查询', null, null, null, null, 4, null, 1, '实时查询', 9, 1, null, 19, '3|8|9|208|', null, null, '/datamgr/sql/execution/showQuery');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (209, 'app_209', null, null, 0, null, '工作日历', null, null, null, null, 4, null, 1, '工作日历', 9, 1, null, 20, '3|8|9|209|', null, null, '/sys/workCalendar/showList');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (210, 'app_210', null, null, 0, null, '系统参数', null, null, null, null, 4, null, 0, '系统参数', 9, 1, null, 9, '3|8|9|210|', null, null, '/sys/property/edit?category=SYS');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (211, 'app_211', null, null, 0, null, '邮件服务设置', null, null, null, null, 4, null, 1, '邮件服务设置', 9, 1, null, 0, '3|8|9|211|', null, null, '/sys/mailConfig');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (212, 'app_212', null, null, 0, null, '系统目录', null, null, null, null, 4, null, 0, '系统目录', 9, 1, null, 10, '3|8|9|212|', null, null, '/sys/tree');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (213, 'app_213', null, null, 0, null, '属性配置', null, null, null, null, 4, null, 1, '属性配置', 9, 1, null, 24, '3|8|9|213|', null, null, '/sys/moduleProperty');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (214, 'app_214', null, null, 0, null, '调度管理', null, null, null, null, 4, null, 0, '调度管理', 9, 1, null, 12, '3|8|9|214|', null, null, '/sys/scheduler');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (300, 'app_300', null, null, 0, null, '个人设置', null, null, null, null, 2, null, 0, '个人设置', 3, 1, null, 1, '3|300|', null, null, null);
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (301, 'app_301', null, null, 0, null, '修改密码', null, null, null, null, 3, null, 0, '修改密码', 300, 1, null, 27, '3|300|301|', null, null, '/user/prepareModifyPwd');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (302, 'app_302', null, null, 0, null, '修改个人信息', null, null, null, null, 3, null, 0, '修改个人信息', 300, 1, null, 28, '3|300|302|', null, null, '/user/prepareModifyInfo');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (1001, 'app_1001', null, '2017-01-16 22:10:47', 0, null, '', null, null, null, '', 0, null, 0, '基础数据表配置', 9, 1, null, 2, '3|8|9|1001|', null, null, '/sys/tableDataItem');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (1901, 'sys_district', null, '2017-02-10 11:40:54', 0, null, '', null, null, null, '', 0, null, 0, '行政区域设置', 9, 1, null, 11, '3|8|9|1901|', null, null, '/sys/district');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (3201, 'app_3201', null, '2017-04-14 16:06:32', 0, null, '', null, null, null, '', 3, null, 0, '数据处理', 8, 0, null, 3, '3|8|3201|', 'admin', '2017-04-14 16:10:49', '');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (3202, 'app_3202', null, '2017-04-14 16:07:04', 0, null, '', null, null, null, '', 4, null, 0, 'SQL语句管理', 3201, 1, null, 0, '3|8|3201|3202|', null, null, '/sys/sql/definition');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (3301, 'app_3301', null, '2017-04-17 10:41:20', 0, null, '', null, null, null, '', 0, null, 0, '图表定义', 3201, 1, null, 0, '3|8|3201|3301|', null, null, '/chart');
 insert into sys_application (id, code, createby, createdate, deleteflag, deletetime, appdesc, discriminator, icon, iconcls, imagepath, level, linktype, locked, name, parentid, showmenu, showtype, sortno, treeid, updateby, updatedate, url ) values (3302, 'app_3302', null, '2017-04-17 10:41:43', 0, null, '', null, null, null, '', 0, null, 0, '报表定义', 3201, 1, null, 0, '3|8|3201|3302|', null, null, '/report');

 
 
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2401, null, 'default_home|default', null, null, '蓝色经典', 'default_home', null, null, null, null, null, null, null, null, null, null, 'default', null, 'default', null, null, null, null, null, null, 0, '蓝色经典', 2148, 1, 'default');
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2402, null, 'default_home|sunny', null, null, '金色阳光', 'default_home', null, null, null, null, null, null, null, null, null, null, 'sunny', null, 'sunny', null, null, null, null, null, null, 0, '金色阳光', 2148, 4, 'sunny');
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2403, null, 'nav_home|default', null, null, '蓝色清新', 'nav_home', null, null, null, null, null, null, null, null, null, null, 'default', null, 'default', null, null, null, null, null, null, 0, '蓝色清新', 2148, 2, 'default');
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2404, null, 'nav_home|sunny', null, null, '金色世纪', 'nav_home', null, null, null, null, null, null, null, null, null, null, 'sunny', null, 'sunny', null, null, null, null, null, null, 0, '金色世纪', 2148, 5, 'sunny');
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2405, null, 'horz_home|gray', null, null, '黑色典雅', 'horz_home', null, null, null, null, null, null, null, null, null, null, 'gray', null, 'gray', null, null, null, null, null, null, 0, '黑色典雅', 2148, 6, 'gray');
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2406, null, 'flat_home|gray', null, null, '扁平黑白', 'flat_home', null, null, null, null, null, null, null, null, null, null, 'gray', null, 'gray', null, null, null, null, null, null, 0, '扁平黑白', 2148, 7, 'gray');
INSERT INTO sys_dictory (ID, CATEGORY, CODE, CREATEBY, CREATEDATE, DICTDESC, EXT1, EXT10, EXT11, EXT12, EXT13, EXT14, EXT15, EXT16, EXT17, EXT18, EXT19, EXT2, EXT20, EXT3, EXT4, EXT5, EXT6, EXT7, EXT8, EXT9, LOCKED, NAME, TYPEID, SORTNO, VALUE_) VALUES (2407, null, 'flat_home|flatblur', null, null, '扁平蓝色', 'flat_home', null, null, null, null, null, null, null, null, null, null, 'flatblur', null, 'sunny', null, null, null, null, null, null, 0, '扁平蓝色', 2148, 3, 'gray');

INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (4, 'EXT1', null, null, 200, 'ext1', 0, 0, 3, 'sys_dictory', '', 'String', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (5, 'EXT2', null, null, 200, 'ext2', 0, 0, 4, 'sys_dictory', '', 'String', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (6, 'EXT3', null, null, 200, 'ext3', 0, 0, 5, 'sys_dictory', '', 'String', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (7, 'EXT4', null, null, 200, 'ext4', 0, 0, 5, 'sys_dictory', '', 'String', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (8, 'EXT5', null, null, 20, 'ext5', 0, 0, 7, 'sys_dictory', '', 'Date', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (9, 'EXT6', null, null, 20, 'ext6', 0, 0, 8, 'sys_dictory', '', 'Date', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (10, 'EXT7', null, null, 20, 'ext7', 0, 0, 9, 'sys_dictory', '', 'Date', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (11, 'EXT8', null, null, 20, 'ext8', 0, 0, 10, 'sys_dictory', '', 'Date', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (12, 'EXT9', null, null, 20, 'ext9', 0, 0, 11, 'sys_dictory', '', 'Date', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (13, 'EXT10', null, null, 20, 'ext10', 0, 0, 12, 'sys_dictory', '', 'Date', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (14, 'EXT11', null, null, 20, 'ext11', 0, 0, 13, 'sys_dictory', '', 'Long', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (15, 'EXT12', null, null, 20, 'ext12', 0, 0, 14, 'sys_dictory', '', 'Long', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (16, 'EXT13', null, null, 20, 'ext13', 0, 0, 15, 'sys_dictory', '', 'Long', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (17, 'EXT14', null, null, 20, 'ext14', 0, 0, 16, 'sys_dictory', '', 'Long', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (18, 'EXT15', null, null, 20, 'ext15', 0, 0, 17, 'sys_dictory', '', 'Long', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (19, 'EXT16', null, null, 20, 'ext16', 0, 0, 18, 'sys_dictory', '', 'Double', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (20, 'EXT17', null, null, 20, 'ext17', 0, 0, 19, 'sys_dictory', '', 'Double', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (21, 'EXT18', null, null, 20, 'ext18', 0, 0, 20, 'sys_dictory', '', 'Double', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (22, 'EXT19', null, null, 20, 'ext19', 0, 0, 21, 'sys_dictory', '', 'Double', null, null);
INSERT INTO sys_dictory_def (ID, COLUMNNAME, CREATEBY, CREATEDATE, LENGTH, NAME, NODEID, REQUIRED, SORTNO, TARGET, TITLE, TYPE, UPDATEBY, UPDATEDATE) VALUES (23, 'EXT20', null, null, 20, 'ext20', 0, 0, 22, 'sys_dictory', '', 'Double', null, null);


INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('1', 'SYS', '系统名称', null, null, 0, null, null, 'res_system_name', '系统名称', null, 'GLAF信息管理系统');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('101', 'RPT', '当天的6位年月格式（YYYYMM），如201312', '${curr_yyyymm}', null, 0, null, null, 'curr_yyyymm', '当前年月', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('102', 'RPT', '当天的8位日期格式（YYYYMMDD），如20130630', '${curr_yyyymmdd}', null, 0, null, null, 'curr_yyyymmdd', '当前日期', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('103', 'RPT', '数据文件路径', null, null, 0, null, null, 'dataDir', '数据文件路径', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('104', 'RPT', '报表输入年月，${curr_yyyymm}表示当前月份', '', null, 0, null, null, 'input_yyyymm', '报表输入年月', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('105', 'RPT', '报表输入的日期，${curr_yyyymmdd}-1表示当前日期的前一天', '', null, 0, null, null, 'input_yyyymmdd', '报表输入日期', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('106', 'RPT', '报表生成根目录', null, null, 0, null, null, 'report_save_path', '报表生成根目录', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('11', 'SYS', '启用查询缓存', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'use_query_cache', '启用查询缓存', null, 'true');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('12', 'SYS', '系统英文名称', null, null, null, null, null, 'res_system_name_en', '系统英文名称', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('131', 'SYS', '开启调试模式', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'debugModeEnable', '开启调试模式', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('132', 'SYS', '启用访问日志', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'enableAccessLog', '启用访问日志', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('14', 'SYS', null, null, null, 0, null, null, 'res_mail_to_dev', '问题报告接收邮箱', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('15', 'SYS', null, null, null, 0, null, null, 'report_service_url', '报表服务器地址', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('18', 'SYS', 'LOGO图片', null, 'imgbox', 0, null, null, 'res_logo', 'LOGO图片', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('2', 'SYS', '系统版本', null, null, 0, null, null, 'res_version', '系统版本', null, 'V3.0');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('213', 'SYS', '内存缓存', '[{"name":"geode","value":"geode"},{"name":"guava","value":"guava"},{"name":"ehcache","value":"ehcache"},{"name":"ehcache3","value":"ehcache3"},{"name":"系统默认","value":""}]', 'combobox', 0, null, null, 'cache_provider', '内存缓存', null, 'guava');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('217', 'SYS', '允许第三方以密锁方式登录', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'login_as_secret_key', '允许第三方以密锁方式登录', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('218', 'SYS', '启用文件缓存', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'use_file_cache', '启用文件缓存', null, 'true');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('3', 'SYS', '版权信息', null, null, 0, null, null, 'res_copyright', '版权信息', null, '版权所有      ');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('31', 'SYS', '一次加载树节点数目', '500', null, 0, null, null, 'treeNodeLoadQty', '一次加载树节点数目', null, '500');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('32', 'SYS', '是否异步写文件', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'useAsynWrite', '是否异步写文件', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('4', 'SYS', null, null, null, 0, null, null, 'res_mail_from', '邮件发送者', null, 'admin@localhost');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('5', 'SYS', '限定每个账号只能在一处登录', '[{"name":"限制","value":"true"},{"name":"不限制","value":"false"}]', 'combobox', 0, null, null, 'login_limit', '系统登录账号限制', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('6', 'SYS', '在线用户检测时间（秒）', null, null, 0, null, null, 'login_time_check', '在线用户检测时间（秒）', null, '600');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('651', 'SYS', null, null, null, 0, null, null, 'serviceUrl', '服务地址', null, 'http://127.0.0.1:8080');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('74', 'SYS', '登录页LOGO图片', null, 'imgbox', 0, null, null, 'res_login_logo', '登录页LOGO图片', null, '/static/images/logo.png');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('8', 'SYS', '允许接入系统的IP地址', null, null, 0, null, null, 'login.allow.ip', '允许接入系统的IP地址', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('80', 'SYS', '系统首页Portal链接', '', null, 0, null, null, 'index_portal_link', '系统首页Portal链接', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('82', 'SYS', '启用分布式资源缓存', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'distributed.resource.enabled', '启用分布式资源缓存', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('83', 'SYS', '启用分布式配置', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'distributed.config.enabled', '启用分布式配置', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('84', 'SYS', '启用二级缓存', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'use_level2_cache', '启用二级缓存', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('85', 'SYS', '分布式资源连接器', '[{"name":"geode","value":"geode"},{"name":"mongodb","value":"mongodb"},{"name":"redis","value":"redis"},{"name":"系统默认","value":""}]', 'combobox', 0, null, null, 'resource.provider', '分布式资源连接器', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('86', 'SYS', '分布式配置连接器', '[{"name":"geode","value":"geode"},{"name":"zookeeper","value":"zookeeper"},{"name":"mongodb","value":"mongodb"},{"name":"redis","value":"redis"},{"name":"系统默认","value":""}]', 'combobox', 0, null, null, 'config.provider', '分布式配置连接器', null, '');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('88', 'SYS', '启用并发访问控制，限制并发访问数量', '[{"name":"是","value":"true"},{"name":"否","value":"false"}]', 'combobox', 0, null, null, 'concurrentAccessLimit', '并发访问控制', null, 'false');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('9', 'SYS', '文件存储方式', '[{"name":"数据库","value":"DATABASE"},{"name":"硬盘","value":"DISK"}]', 'combobox', 0, null, null, 'fs_storage_strategy', '文件存储方式', null, 'DATABASE');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('INT_TOKEN', 'SYS', null, null, null, 0, null, null, 'INT_TOKEN', 'INT_TOKEN', 'String', '2017');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('TOKEN', 'SYS', null, null, null, 0, null, null, 'TOKEN', 'TOKEN', 'String', '4310374942be7e324e47bdfae8139dcaff137128');
INSERT INTO sys_property (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, INPUTTYPE_, LOCKED_, MAXVALUE_, MINVALUE_, NAME_, TITLE_, TYPE_, VALUE_) VALUES ('tabmax', 'SYS', '主页选卡打开数', null, null, 0, null, null, 'tabmax', '主页选卡打开数', null, '10');
INSERT INTO SYS_PROPERTY (ID_, CATEGORY_, DESCRIPTION_, INITVALUE_, LOCKED_, NAME_, TITLE_, TYPE_, VALUE_, INPUTTYPE_) values ('RunEnvironment', 'SYS', '系统运行环境', '[{"name":"开发环境","value":"dev"},{"name":"测试环境","value":"test"},{"name":"生产环境","value":"product"}]', 0, 'RunEnvironment', '系统运行环境', null, 'dev', 'combobox');


INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('AnyOne', 'AnyOne', '普通用户', 'system', '2017-01-15 17:49:12', 0, null, '', '', '普通用户', 0, 'SYS', 'admin', '2017-01-26 20:24:25', 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('AttendanceManagement', 'AttendanceManagement', '考勤管理员', 'system', null, 0, null, '', null, '考勤管理员', 6, 'SYS', null, null, 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('Auditor', 'Auditor', '审计员', 'system', null, 0, null, '', '', '审计员', 0, 'SYS', 'admin', '2017-01-26 20:24:48', 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('Buyer', 'Buyer', '采购员', 'system', null, 0, null, '', null, '采购员', 8, 'SYS', null, null, 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('Keyboarder', 'Keyboarder', '资料录入员', 'system', '2017-01-18 17:17:47', 0, null, '', '', '资料录入员', 0, 'SYS', 'admin', '2017-01-26 20:24:15', 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('SeniorManager', 'SeniorManager', '高级经理', 'system', null, 0, null, '', null, '高级经理', 4, 'SYS', null, null, 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('StockManager', 'StockManager', '库房管理员', 'system', null, 0, null, '', null, '库房管理员', 7, 'SYS', null, null, 'Y');
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('SystemAdministrator', 'SystemAdministrator', '系统管理员', 'system', null, 0, null, '/sys/tenant', null, '系统管理员', 1, 'SYS', null, '2017-01-03 17:03:17', null);
INSERT INTO sys_role (ID, CODE, CONTENT, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, INDEXURL, ISUSEBRANCH, ROLENAME, SORTNO, TYPE, UPDATEBY, UPDATEDATE, ISUSEORGANIZATION) VALUES ('TenantAdmin', 'TenantAdmin', '租户管理员', 'system', null, 0, null, '', null, '租户管理员', 2, 'SYS', null, null, null);


INSERT INTO sys_scheduler (ID, ATTRIBUTE_, AUTOSTARTUP, CONTENT, CREATEBY, CREATEDATE, ENDDATE, EXPRESSION_, FIRETIME, INTERVALTIME, INTERVALTYPE, INTERVALVALUE, JOBCLASS, JOBRUNTIME, LOCKED_, METHODNAME, NEXTFIRETIME, PREVIOUSFIRETIME, PRIORITY_, REPEATCOUNT, REPEATINTERVAL, RUNSTATUS, RUNTYPE, SPRINGBEANID, SPRINGCLASS, STARTDATE, STARTDELAY, STARTUP_, TASKNAME, TASKTYPE, THREADSIZE, TITLE) VALUES ('102846', null, 1, null, 'admin', '2017-01-07 19:51:43', '2099-01-31 19:51:34', '0 0/25 * * * ?', '2017-04-19 11:25:00', null, null, null, 'com.glaf.base.job.BaseDataRefreshJob', 37, 0, null, '2017-04-19 11:50:00', '2017-04-19 11:25:00', 0, 0, 0, 0, 1, null, null, '2017-01-01 19:51:32', 0, 1, '重新装载基础数据Job', '', 0, '重新装载基础数据Job');
INSERT INTO sys_scheduler (ID, ATTRIBUTE_, AUTOSTARTUP, CONTENT, CREATEBY, CREATEDATE, ENDDATE, EXPRESSION_, FIRETIME, INTERVALTIME, INTERVALTYPE, INTERVALVALUE, JOBCLASS, JOBRUNTIME, LOCKED_, METHODNAME, NEXTFIRETIME, PREVIOUSFIRETIME, PRIORITY_, REPEATCOUNT, REPEATINTERVAL, RUNSTATUS, RUNTYPE, SPRINGBEANID, SPRINGCLASS, STARTDATE, STARTDELAY, STARTUP_, TASKNAME, TASKTYPE, THREADSIZE, TITLE) VALUES ('113908', null, 1, null, 'admin', '2017-02-15 19:05:17', '2020-02-29 19:05:08', '0 0/15 * * * ?', '2017-04-19 11:30:00', null, null, null, 'com.glaf.core.cache.ClearCacheJob', 59, 0, null, '2017-04-19 11:45:00', '2017-04-19 11:30:00', 0, 0, 3600, 2, 1, null, null, '2017-02-01 19:05:06', 0, 1, '清除缓存对象', '', 0, '清除缓存对象');
INSERT INTO sys_scheduler (ID, ATTRIBUTE_, AUTOSTARTUP, CONTENT, CREATEBY, CREATEDATE, ENDDATE, EXPRESSION_, FIRETIME, INTERVALTIME, INTERVALTYPE, INTERVALVALUE, JOBCLASS, JOBRUNTIME, LOCKED_, METHODNAME, NEXTFIRETIME, PREVIOUSFIRETIME, PRIORITY_, REPEATCOUNT, REPEATINTERVAL, RUNSTATUS, RUNTYPE, SPRINGBEANID, SPRINGCLASS, STARTDATE, STARTDELAY, STARTUP_, TASKNAME, TASKTYPE, THREADSIZE, TITLE) VALUES ('116202', null, 1, null, 'admin', '2017-02-26 22:09:27', '2020-02-29 22:09:16', '0 0/5 * * * ?', '2017-02-27 22:05:00', null, null, null, 'com.glaf.matrix.data.job.TablesToSqliteDBJob', 2936, 1, null, '2017-02-27 22:10:00', '2017-02-27 22:05:00', 0, 0, 0, 0, 1, null, null, '2017-02-26 22:09:13', 0, 1, '备份数据到SQLite', '', 0, '备份数据到SQLite');


INSERT INTO sys_tenant (ID_, CODE_, CREATEBY_, CREATETIME_, DATABASEID_, LOCKED_, NAME_, PRINCIPAL_, TELEPHONE_, TENANTID_, TENANTTYPE_, UPDATEBY_, UPDATETIME_) VALUES (1, 'sys', 'sys', null, 1, 0, 'sys', null, null, '1', 1, null, null);

INSERT INTO sys_tree (ID, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, CODE, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, NODEDESC, DISCRIMINATOR, ICON, ICONCLS, LOCKED, MOVEABLE, NAME, PARENTID, PROVIDERCLASS, SORTNO, TREEID, UPDATEBY, UPDATEDATE, URL, LEVEL, VALUE_) VALUES (1, null, null, '0', 'admin', null, 0, null, '根目录', null, null, null, 0, null, '/根目录', -1, null, 1, '1|', null, null, null, 1, null);
INSERT INTO sys_tree (ID, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, CODE, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, NODEDESC, DISCRIMINATOR, ICON, ICONCLS, LOCKED, MOVEABLE, NAME, PARENTID, PROVIDERCLASS, SORTNO, TREEID, UPDATEBY, UPDATEDATE, URL, LEVEL, VALUE_) VALUES (2, null, null, '01', 'admin', null, 0, null, '数据结构', null, null, null, 0, null, '数据结构', 1, null, 20, '1|2|', null, null, null, 2, null);
INSERT INTO sys_tree (ID, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, CODE, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, NODEDESC, DISCRIMINATOR, ICON, ICONCLS, LOCKED, MOVEABLE, NAME, PARENTID, PROVIDERCLASS, SORTNO, TREEID, UPDATEBY, UPDATEDATE, URL, LEVEL, VALUE_) VALUES (4, null, null, '011', 'admin', null, 0, null, '基础数据', null, null, null, 0, null, '基础数据', 2, null, 50, '1|2|4|', null, null, null, 3, null);
INSERT INTO sys_tree (ID, ALLOWEDFILEEXTS, ALLOWEDFIZESIZE, CODE, CREATEBY, CREATEDATE, DELETEFLAG, DELETETIME, NODEDESC, DISCRIMINATOR, ICON, ICONCLS, LOCKED, MOVEABLE, NAME, PARENTID, PROVIDERCLASS, SORTNO, TREEID, UPDATEBY, UPDATEDATE, URL, LEVEL, VALUE_) VALUES (2148, null, null, 'dict_theme', 'admin', null, 0, null, '主题定义', 'T', null, null, 0, null, '主题定义', 4, null, 1, '1|2|4|2148|', null, null, null, 4, null);

INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170715, 15, 7, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170716, 16, 7, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170722, 22, 7, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170723, 23, 7, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170729, 29, 7, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170730, 30, 7, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170805, 5, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170806, 6, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170812, 12, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170813, 13, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170819, 19, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170820, 20, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170826, 26, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170827, 27, 8, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170902, 2, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170903, 3, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170909, 9, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170910, 10, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170916, 16, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170917, 17, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170923, 23, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170924, 24, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20170930, 30, 9, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171001, 1, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171002, 2, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171003, 3, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171004, 4, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171005, 5, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171006, 6, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171007, 7, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171008, 8, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171014, 14, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171015, 15, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171021, 21, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171022, 22, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171028, 28, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171029, 29, 10, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171104, 4, 11, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171105, 5, 11, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171111, 11, 11, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171112, 12, 11, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171118, 18, 11, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171119, 19, 11, 2017);
INSERT INTO sys_workcalendar (ID, FREEDAY, FREEMONTH, FREEYEAR) VALUES (20171125, 25, 11, 2017);



INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_AGGREGATION_DEF', '系统内置主键', '201', 3);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_APPLICATION', '系统内置主键', '3401', 26);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_DATABASE', '系统内置主键', '401', 5);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_SCHEDULER_EXECUTION', '系统内置主键', '21301', 214);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_SQL', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_SQL_CRITERIA', '系统内置主键', '301', 4);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TABLE_CORRELATION', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TABLE_DATA_ITEM', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TABLE_PERMISSION', '系统内置主键', '201', 3);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TENANT', '系统内置主键', '100001', 4);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TENANT_CONFIG', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TENANT_FOLLOW', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TENANT_GRANT', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('SYS_TREE_PERMISSION', '系统内置主键', '101', 2);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('next.dbid', '系统内置主键', '123401', 1234);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('sys_scheduler_execution', '系统内置主键', '301', 4);
INSERT INTO sys_dbid (NAME_, TITLE_, VALUE_, VERSION_) VALUES ('useradd', '系统内置主键', '1501', 15);
